name: Memory Chain Workflow
version: 1.0.0
description: Persistent memory storage and retrieval for MemoryVault

trigger:
  type: user_action
  page: P103 (MemoryVault)
  action: memory_operation

workflow:
  - step: 1
    name: Memory Retrieval
    agent: memory-vault
    tool: list_memories
    description: List all stored memories
    output: memory_list

  - step: 2
    name: Memory Read
    agent: memory-vault
    tool: read_memory
    input: ${selected_memory_id}
    description: Read specific memory content
    output: memory_content

  - step: 3
    name: Memory Analysis
    agent: browser-automation
    tool: analyze_content
    input: ${memory_content}
    description: Analyze memory for patterns
    output: analysis_result

  - step: 4
    name: Memory Write
    agent: memory-vault
    tool: write_memory
    input:
      content: ${new_memory}
      tags: ${memory_tags}
      timestamp: ${current_time}
    description: Store new memory
    output: memory_id

  - step: 5
    name: Memory Search
    agent: memory-vault
    tool: search_memories
    input: ${search_query}
    description: Search memories by keyword
    output: search_results

error_handling:
  - condition: memory_not_found
    action: return_empty
    message: "No memories found"
  
  - condition: storage_full
    action: cleanup
    strategy: oldest_first
    keep_count: 1000

  - condition: corruption_detected
    action: repair
    backup_source: localStorage

caching:
  memory_list:
    ttl: 60 # 1 minute
    invalidate_on: write_operation
  
  memory_content:
    ttl: 300 # 5 minutes
    invalidate_on: update

integration:
  pages:
    - P103 (MemoryVault)
  
  hooks:
    - on_memory_created
    - on_memory_deleted
    - on_memory_updated

  services:
    - MemoryAgent
    - PersonalityService (for memory narration)
