// 500s - VIBE
export function WellnessPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P501 WELLNESS</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">💪 HEALTH & FITNESS TIPS</p></div><div className="px-3 mt-3"><p className="text-yellow text-xl font-bold mb-2">TODAY'S WORKOUT:</p><div className="border-2 border-magenta p-3 bg-magenta/10"><p className="text-white text-lg font-bold">30-MIN FULL BODY</p><div className="mt-2 space-y-1 text-base"><p className="text-cyan">• Warm-up: 5 min</p><p className="text-cyan">• Push-ups: 3x15</p><p className="text-cyan">• Squats: 3x20</p><p className="text-cyan">• Plank: 3x60s</p><p className="text-cyan">• Cool-down: 5 min</p></div></div></div><div className="px-3 mt-3"><div className="grid grid-cols-2 gap-2"><div className="border border-green p-2"><p className="text-green font-bold text-lg">SLEEP</p><p className="text-white text-2xl">7-9h</p></div><div className="border border-cyan p-2"><p className="text-cyan font-bold text-lg">WATER</p><p className="text-white text-2xl">2-3L</p></div></div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">WELLNESS - DAILY HEALTH TIPS</span></div></div>
}

export function NutritionPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P502 NUTRITION</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🥗 MEAL PLANS & DIETARY ADVICE</p></div><div className="px-3 mt-3"><p className="text-yellow text-xl font-bold mb-2">TODAY'S MEAL PLAN:</p><div className="space-y-2"><div className="border border-yellow p-2 bg-black/50"><p className="text-yellow font-bold">BREAKFAST</p><p className="text-white">Oatmeal + Berries + Nuts</p><p className="text-cyan text-sm">450 cal | 12g protein</p></div><div className="border border-green p-2 bg-black/50"><p className="text-green font-bold">LUNCH</p><p className="text-white">Grilled Chicken Salad</p><p className="text-cyan text-sm">550 cal | 35g protein</p></div><div className="border border-cyan p-2 bg-black/50"><p className="text-cyan font-bold">DINNER</p><p className="text-white">Salmon + Quinoa + Veggies</p><p className="text-cyan text-sm">600 cal | 40g protein</p></div></div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">NUTRITION - HEALTHY EATING GUIDE</span></div></div>
}

export function MindfulnessPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P503 MINDFULNESS</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🧘 MEDITATION & MENTAL HEALTH</p></div><div className="px-3 mt-3"><div className="border-2 border-cyan p-4 bg-cyan/10 text-center"><p className="text-cyan text-2xl font-bold mb-3">BREATHE</p><p className="text-white text-xl">Inhale... 4s</p><p className="text-white text-xl">Hold... 4s</p><p className="text-white text-xl">Exhale... 4s</p><p className="text-white text-xl">Hold... 4s</p><p className="text-cyan text-base mt-3">Repeat 5 times</p></div></div><div className="px-3 mt-3"><p className="text-yellow text-lg font-bold mb-2">DAILY AFFIRMATIONS:</p><div className="border border-magenta p-3 bg-black/50 text-white text-base space-y-1"><p>• I am capable and strong</p><p>• I choose peace over worry</p><p>• I am grateful for today</p><p>• I trust the process</p></div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">MINDFULNESS - FIND YOUR CALM</span></div></div>
}

export function LifestylePage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P504 LIFESTYLE</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">✨ TRENDS & PERSONAL DEVELOPMENT</p></div><div className="px-3 mt-3"><p className="text-yellow text-xl font-bold mb-2">🔥 TRENDING NOW:</p><div className="space-y-2"><div className="border-l-4 border-yellow pl-3 py-2"><p className="text-white text-lg font-bold">Minimalist Living</p><p className="text-cyan text-sm">Declutter your space, clear your mind</p></div><div className="border-l-4 border-green pl-3 py-2"><p className="text-white text-lg font-bold">Digital Detox</p><p className="text-cyan text-sm">Unplug for better mental health</p></div><div className="border-l-4 border-cyan pl-3 py-2"><p className="text-white text-lg font-bold">Sustainable Fashion</p><p className="text-cyan text-sm">Eco-friendly wardrobe choices</p></div></div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">LIFESTYLE - LIVE YOUR BEST LIFE</span></div></div>
}

// 600s - CREATOR
export function MusicChartsPage() {
  const songs = [{pos:1,title:'FLOWERS',artist:'Miley Cyrus',weeks:12},{pos:2,title:'ANTI-HERO',artist:'Taylor Swift',weeks:8},{pos:3,title:'CALM DOWN',artist:'Rema & Selena',weeks:15},{pos:4,title:'UNHOLY',artist:'Sam Smith',weeks:6},{pos:5,title:'AS IT WAS',artist:'Harry Styles',weeks:20}]
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P601 MUSIC CHARTS</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🎵 TOP 100 • UPDATED WEEKLY</p></div><div className="px-2 mt-3"><div className="bg-magenta text-black font-bold text-sm p-1 grid grid-cols-12 gap-1"><span className="col-span-1">#</span><span className="col-span-6">SONG</span><span className="col-span-4">ARTIST</span><span className="col-span-1">WK</span></div>{songs.map((s,i)=><div key={i} className={`text-sm p-1 grid grid-cols-12 gap-1 border-b border-magenta/30 ${i%2===0?'bg-black/50':'bg-magenta/5'}`}><span className="col-span-1 text-yellow font-bold">{s.pos}</span><span className="col-span-6 text-white font-bold">{s.title}</span><span className="col-span-4 text-cyan">{s.artist}</span><span className="col-span-1 text-white">{s.weeks}</span></div>)}</div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">MUSIC CHARTS - BILLBOARD HOT 100</span></div></div>
}

export function MovieReviewsPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P602 MOVIES</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🎬 REVIEWS & CINEMA LISTINGS</p></div><div className="px-3 mt-3"><div className="border-2 border-yellow p-3 bg-yellow/10"><p className="text-yellow text-xl font-bold">OPPENHEIMER</p><p className="text-white text-lg mt-1">★★★★★ 9.2/10</p><p className="text-cyan text-base mt-2">"A masterpiece of modern cinema. Nolan's best work yet."</p><p className="text-white text-sm mt-2">Drama • 3h • PG-13</p></div></div><div className="px-3 mt-3 space-y-2">{[{title:'BARBIE',rating:'★★★★☆',score:'8.5'},{title:'DUNE PART TWO',rating:'★★★★★',score:'9.0'},{title:'POOR THINGS',rating:'★★★★☆',score:'8.3'}].map((m,i)=><div key={i} className="border border-magenta p-2 bg-black/50"><div className="flex justify-between"><span className="text-white font-bold">{m.title}</span><span className="text-yellow">{m.rating}</span></div><span className="text-cyan text-sm">{m.score}/10</span></div>)}</div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">MOVIE REVIEWS - ROTTEN TOMATOES</span></div></div>
}

export function ArtGalleryPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P603 ART GALLERY</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🎨 DIGITAL EXHIBITIONS & ARTISTS</p></div><div className="px-3 mt-3"><p className="text-yellow text-xl font-bold mb-2">FEATURED EXHIBITION:</p><div className="border-2 border-cyan p-3 bg-cyan/10"><p className="text-cyan text-xl font-bold">NEON DREAMS</p><p className="text-white text-lg mt-2">Digital Art Collection</p><p className="text-white text-base mt-2">Artist: Alex Chen</p><p className="text-yellow text-base mt-1">Feb 15 - Mar 30, 2078</p></div></div><div className="px-3 mt-3"><p className="text-yellow text-lg font-bold mb-2">TRENDING ARTISTS:</p><div className="space-y-1 text-base">{['Beeple - NFT Pioneer','Refik Anadol - AI Art','Pak - Crypto Artist'].map((a,i)=><p key={i} className="text-cyan">• {a}</p>)}</div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">ART GALLERY - DIGITAL EXHIBITIONS</span></div></div>
}

export function CreatorToolsPage() {
  return <div className="teletext-page"><div className="teletext-title-banner bg-magenta"><span className="double-height text-black">P604 CREATOR TOOLS</span></div><div className="px-3 py-2 bg-black border-b border-magenta"><p className="text-magenta text-base">🛠️ RESOURCES FOR CONTENT CREATORS</p></div><div className="px-3 mt-3"><p className="text-yellow text-xl font-bold mb-2">ESSENTIAL TOOLS:</p><div className="space-y-2">{[{name:'Adobe Creative Cloud',cat:'Design',price:'$54.99/mo'},{name:'Final Cut Pro',cat:'Video',price:'$299.99'},{name:'Logic Pro',cat:'Audio',price:'$199.99'},{name:'Figma',cat:'UI/UX',price:'Free'}].map((t,i)=><div key={i} className="border border-cyan p-2 bg-black/50"><div className="flex justify-between"><div><p className="text-white font-bold">{t.name}</p><p className="text-cyan text-sm">{t.cat}</p></div><p className="text-green font-bold">{t.price}</p></div></div>)}</div></div><div className="teletext-bottom-banner bg-magenta"><span className="text-black">CREATOR TOOLS - BUILD YOUR BRAND</span></div></div>
}
